<?php

namespace Italia\SPIDAuth\Tests\Models;

use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use Italia\SPIDAuth\Models\SPIDTransaction;
use Italia\SPIDAuth\Tests\SPIDAuthBaseTestCase;

class SPIDTransactionTest extends SPIDAuthBaseTestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();

        if (!Schema::hasTable('spid_transactions')) {
            Schema::create('spid_transactions', function ($table) {
                $table->id();
                $table->uuid('uuid')->unique();
                $table->string('authn_request_id')->nullable()->index();
                $table->timestamp('authn_request_issue_instant')->nullable();
                $table->longText('authn_request_xml')->nullable();
                $table->string('response_id')->nullable();
                $table->timestamp('response_issue_instant')->nullable();
                $table->string('response_issuer')->nullable()->index();
                $table->longText('response_xml')->nullable();
                $table->string('assertion_id')->nullable();
                $table->string('assertion_subject')->nullable();
                $table->string('assertion_subject_name_qualifier')->nullable();
                $table->string('idp_entity_id')->nullable()->index();
                $table->string('sp_entity_id')->nullable();
                $table->string('spid_level', 50)->nullable();
                $table->string('status_code')->nullable();
                $table->string('relay_state')->nullable();
                $table->timestamps();
                $table->index('created_at');
            });
        }
    }

    public function testUuidIsAutoGeneratedOnCreate()
    {
        $transaction = SPIDTransaction::create([
            'idp_entity_id' => 'test-idp',
            'authn_request_id' => 'req-1',
        ]);

        $this->assertNotNull($transaction->uuid);
        $this->assertTrue(Str::isUuid($transaction->uuid));
    }

    public function testUuidIsNotOverwrittenWhenPreSet()
    {
        $customUuid = (string) Str::uuid();

        $transaction = SPIDTransaction::create([
            'uuid' => $customUuid,
            'idp_entity_id' => 'test-idp',
            'authn_request_id' => 'req-1',
        ]);

        $this->assertSame($customUuid, $transaction->uuid);
    }

    public function testEachRecordGetsUniqueUuid()
    {
        $t1 = SPIDTransaction::create([
            'idp_entity_id' => 'test-idp',
            'authn_request_id' => 'req-1',
        ]);

        $t2 = SPIDTransaction::create([
            'idp_entity_id' => 'test-idp',
            'authn_request_id' => 'req-2',
        ]);

        $this->assertNotSame($t1->uuid, $t2->uuid);
    }

    public function testUuidIsCastToString()
    {
        $transaction = SPIDTransaction::create([
            'idp_entity_id' => 'test-idp',
            'authn_request_id' => 'req-1',
        ]);

        $transaction->refresh();
        $this->assertIsString($transaction->uuid);
    }

    public function testDatetimeCastsForIssueInstants()
    {
        $transaction = SPIDTransaction::create([
            'idp_entity_id' => 'test-idp',
            'authn_request_id' => 'req-1',
            'authn_request_issue_instant' => '2024-01-15 12:00:00',
            'response_issue_instant' => '2024-01-15 12:00:05',
        ]);

        $transaction->refresh();
        $this->assertInstanceOf(Carbon::class, $transaction->authn_request_issue_instant);
        $this->assertInstanceOf(Carbon::class, $transaction->response_issue_instant);
    }

    public function testAllNewFieldsAreFillable()
    {
        $transaction = SPIDTransaction::create([
            'idp_entity_id' => 'https://idp.example.com',
            'sp_entity_id' => 'https://sp.example.com',
            'authn_request_id' => 'req-1',
            'authn_request_issue_instant' => '2024-01-15 12:00:00',
            'authn_request_xml' => '<xml>request</xml>',
            'response_id' => 'resp-1',
            'response_issue_instant' => '2024-01-15 12:00:05',
            'response_issuer' => 'https://idp.example.com',
            'response_xml' => '<xml>response</xml>',
            'assertion_id' => 'assertion-1',
            'assertion_subject' => 'user@example.com',
            'assertion_subject_name_qualifier' => 'https://idp.example.com',
            'spid_level' => 'https://www.spid.gov.it/SpidL2',
            'status_code' => 'urn:oasis:names:tc:SAML:2.0:status:Success',
            'relay_state' => '/dashboard',
        ]);

        $transaction->refresh();

        $this->assertSame('https://idp.example.com', $transaction->idp_entity_id);
        $this->assertSame('https://sp.example.com', $transaction->sp_entity_id);
        $this->assertSame('req-1', $transaction->authn_request_id);
        $this->assertSame('<xml>request</xml>', $transaction->authn_request_xml);
        $this->assertSame('resp-1', $transaction->response_id);
        $this->assertSame('https://idp.example.com', $transaction->response_issuer);
        $this->assertSame('<xml>response</xml>', $transaction->response_xml);
        $this->assertSame('assertion-1', $transaction->assertion_id);
        $this->assertSame('user@example.com', $transaction->assertion_subject);
        $this->assertSame('https://idp.example.com', $transaction->assertion_subject_name_qualifier);
        $this->assertSame('https://www.spid.gov.it/SpidL2', $transaction->spid_level);
        $this->assertSame('urn:oasis:names:tc:SAML:2.0:status:Success', $transaction->status_code);
        $this->assertSame('/dashboard', $transaction->relay_state);
    }

    public function testNullableFieldsCanBeNull()
    {
        $transaction = SPIDTransaction::create([
            'authn_request_id' => 'req-1',
        ]);

        $transaction->refresh();

        $this->assertNull($transaction->idp_entity_id);
        $this->assertNull($transaction->sp_entity_id);
        $this->assertNull($transaction->authn_request_issue_instant);
        $this->assertNull($transaction->authn_request_xml);
        $this->assertNull($transaction->response_id);
        $this->assertNull($transaction->response_issue_instant);
        $this->assertNull($transaction->response_issuer);
        $this->assertNull($transaction->response_xml);
        $this->assertNull($transaction->assertion_id);
        $this->assertNull($transaction->assertion_subject);
        $this->assertNull($transaction->assertion_subject_name_qualifier);
        $this->assertNull($transaction->spid_level);
        $this->assertNull($transaction->status_code);
        $this->assertNull($transaction->relay_state);
    }

    public function testScopeOlderThanFiltersCorrectly()
    {
        SPIDTransaction::create([
            'authn_request_id' => 'old',
            'created_at' => Carbon::now()->subMonths(25),
        ]);

        SPIDTransaction::create([
            'authn_request_id' => 'recent',
            'created_at' => Carbon::now()->subMonths(5),
        ]);

        $cutoff = Carbon::now()->subMonths(24);
        $oldTransactions = SPIDTransaction::olderThan($cutoff)->get();

        $this->assertSame(1, $oldTransactions->count());
        $this->assertSame('old', $oldTransactions->first()->authn_request_id);
    }

    public function testScopeOlderThanReturnsEmptyWhenNoneMatch()
    {
        SPIDTransaction::create([
            'authn_request_id' => 'recent',
            'created_at' => Carbon::now()->subDays(1),
        ]);

        $cutoff = Carbon::now()->subMonths(24);
        $oldTransactions = SPIDTransaction::olderThan($cutoff)->get();

        $this->assertSame(0, $oldTransactions->count());
    }

    public function testTableNameIsCorrect()
    {
        $transaction = new SPIDTransaction();
        $this->assertSame('spid_transactions', $transaction->getTable());
    }

    public function testTimestampsAreEnabled()
    {
        $transaction = SPIDTransaction::create([
            'authn_request_id' => 'req-1',
        ]);

        $this->assertNotNull($transaction->created_at);
        $this->assertNotNull($transaction->updated_at);
    }

    public function testUpdatePreservesUuid()
    {
        $transaction = SPIDTransaction::create([
            'idp_entity_id' => 'test-idp',
            'authn_request_id' => 'req-1',
        ]);

        $originalUuid = $transaction->uuid;

        $transaction->update([
            'response_id' => 'resp-1',
            'status_code' => 'urn:oasis:names:tc:SAML:2.0:status:Success',
        ]);

        $transaction->refresh();
        $this->assertSame($originalUuid, $transaction->uuid);
        $this->assertSame('resp-1', $transaction->response_id);
    }

    protected function getEnvironmentSetUp($app)
    {
        parent::getEnvironmentSetUp($app);

        $app['config']->set('database.default', 'testing');
        $app['config']->set('database.connections.testing', [
            'driver' => 'sqlite',
            'database' => ':memory:',
            'prefix' => '',
        ]);
    }
}
